### ISSUE TITLE
Error: unable to open object pack directory

### ISSUE THREAD

**Issue by griccitiello** [OpenMage/migrate#5]
I've got this error, any clue how to fix it?

error: unable to open object pack directory: /dev/null/objects/pack: Not a directory
error: unable to open object pack directory: /dev/null/objects/pack: Not a directory
error: unable to open object pack directory: /dev/null/objects/pack: Not a directory
Unable to apply the patch. The following command failed:

    git --git-dir=/dev/null apply --ignore-whitespace --check var/magento-ce-1.9.4.5-openmage-lts-v19.4.8.patch

**Comment by colinmollenhour** [comment]
Permission issue? Otherwise no idea, I've never seen that error before.
